// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQsD4aIPQnOzj_12_w49v0REB2O2cWPE',
    appId: '1:777718294130:web:d1919e16adf0cdbdbf84eb',
    messagingSenderId: '777718294130',
    projectId: 'sehatapp-c0c8b',
    authDomain: 'sehatapp-c0c8b.firebaseapp.com',
    storageBucket: 'sehatapp-c0c8b.firebasestorage.app',
    measurementId: 'G-K1EZ4KF25N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5V76aZ5ubYRAGRrSzCONsW-xuaKAlDOs',
    appId: '1:777718294130:android:c9257d8a3b658abdbf84eb',
    messagingSenderId: '777718294130',
    projectId: 'sehatapp-c0c8b',
    storageBucket: 'sehatapp-c0c8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTUNbjahGkV-GdxbtDLbPrgVx_HrquY0',
    appId: '1:777718294130:ios:5b2d6e01a3926036bf84eb',
    messagingSenderId: '777718294130',
    projectId: 'sehatapp-c0c8b',
    storageBucket: 'sehatapp-c0c8b.firebasestorage.app',
    iosClientId: '777718294130-e1gp00qro101tih6hb2md504e5j5rfi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sehatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuTUNbjahGkV-GdxbtDLbPrgVx_HrquY0',
    appId: '1:777718294130:ios:5b2d6e01a3926036bf84eb',
    messagingSenderId: '777718294130',
    projectId: 'sehatapp-c0c8b',
    storageBucket: 'sehatapp-c0c8b.firebasestorage.app',
    iosClientId: '777718294130-e1gp00qro101tih6hb2md504e5j5rfi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sehatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcQsD4aIPQnOzj_12_w49v0REB2O2cWPE',
    appId: '1:777718294130:web:4e614292e0244442bf84eb',
    messagingSenderId: '777718294130',
    projectId: 'sehatapp-c0c8b',
    authDomain: 'sehatapp-c0c8b.firebaseapp.com',
    storageBucket: 'sehatapp-c0c8b.firebasestorage.app',
    measurementId: 'G-ZE45R41EPR',
  );
}
